### PR TITLE
[waiting for CI to finish] AppVeyor: Always download DUB to avoid issues with missing bundles and remove LDC 32-bit builds

### PR DESCRIPTION
**Pull request by wilzbach**
Short follow-up to https://github.com/etcimon/libasync/pull/78

Most of the failures are due to a non-existent DUB binary in old releases, which this addition should fix - it takes about 10s to download and extract DUB, so the overhead is neglectable and this is also the way the `appveyor.yml` used to work.

However, there also seem to be weird linking errors with ldc in 32-bit mode:

```
libasync 0.8.3+commit.4.g44f4663: building configuration "libasync-test-regular"...
Enhanced memory security is enabled.
Memory debugger enabled
Using Windows message-based notifications and alertable IO for events
ws2_32_ex.lib : fatal error LNK1136: invalid or corrupt file
Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe failed with status: 1136
ldc2 failed with exit code 1136.
```

E.g.
https://ci.appveyor.com/project/etcimon/libasync/build/0.7.9.32/job/7lnfrmb5yirmlld7

Hence, for now at least I removed the 32-bit LDC builds.

### CODE REVIEW

**Comment by wilzbach** [comment]
Hmm, `libasync` doesn't seem to work with 2.068.2 anymore. Do you still intend to support it for this platform or should I simply remove the older, failing versions?

```
source\libasync\windows.d(775,28): Error: core.sys.windows.winsock2.SOL_SOCKET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(294,5) conflicts with core.sys.windows.winsock2.SOL_SOCKET at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(775,40): Error: core.sys.windows.winsock2.SO_REUSEADDR at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(302,5) conflicts with core.sys.windows.winsock2.SO_REUSEADDR at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(318,28)
source\libasync\windows.d(792,28): Error: core.sys.windows.winsock2.SOL_SOCKET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(294,5) conflicts with core.sys.windows.winsock2.SOL_SOCKET at source\libasync\internals\socket_compat.d(19,16)
source\libasync\events.d(161,28): Error: template instance libasync.windows.EventLoopImpl.setOption!bool error instantiating
source\libasync\tcp.d(58,28):        instantiated from here: setOption!bool
source\libasync\tcp.d(51,13):        instantiated from here: setOption!bool
source\libasync\windows.d(139,29): Error: core.sys.windows.winsock2.AF_INET6 at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(253,5) conflicts with core.sys.windows.winsock2.AF_INET6 at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(286,21)
source\libasync\windows.d(139,39): Error: core.sys.windows.winsock2.SOCK_STREAM at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(524,5) conflicts with core.sys.windows.winsock2.SOCK_STREAM at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(190,20): Error: undefined identifier 'CreateEvent', did you mean function 'CreateEventW'?
source\libasync\windows.d(192,20): Error: undefined identifier 'CreateEvent', did you mean function 'CreateEventW'?
source\libasync\windows.d(79,7): Error: function libasync.windows.EventLoopImpl.init no return exp; or assert(0); at end of function
source\libasync\windows.d(1230,33): Error: core.sys.windows.winsock2.SOL_SOCKET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(294,5) conflicts with core.sys.windows.winsock2.SOL_SOCKET at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(417,48): Error: core.sys.windows.winsock2.SOCK_STREAM at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(524,5) conflicts with core.sys.windows.winsock2.SOCK_STREAM at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(468,47): Error: core.sys.windows.winsock2.SOCK_STREAM at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(524,5) conflicts with core.sys.windows.winsock2.SOCK_STREAM at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(516,48): Error: core.sys.windows.winsock2.SOCK_DGRAM at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(525,5) conflicts with core.sys.windows.winsock2.SOCK_DGRAM at source\libasync\internals\socket_compat.d(19,16)
source\libasync\windows.d(1173,10): Error: core.sys.windows.winsock2.AF_INET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(230,5) conflicts with core.sys.windows.winsock2.AF_INET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(265,21)
source\libasync\windows.d(1174,34): Error: core.sys.windows.winsock2.AF_INET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(230,5) conflicts with core.sys.windows.winsock2.AF_INET at C:\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\winsock2.d(265,21)
dmd failed with exit code 1.
```

https://ci.appveyor.com/project/etcimon/libasync/build/job/aidt2et8hkjvf83a

**Comment by etcimon** [comment]
There's a lot of conflicts, I'm guessing it should have a `static if __VERSION__` tag somewhere

**Comment by etcimon** [comment]
These versions are pretty old I'd probably just remove support for <2.069
